version: "3.9"
services:
  mysql:
    image: mysql:8
    container_name: hospital-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospital_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./hospital-backend
    container_name: hospital-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hospital_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      - mysql

  frontend:
    build: ./hospital-frontend
    container_name: hospital-frontend
    environment:
      VITE_API_URL: http://localhost:8081
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mysql_data:
